### ISSUE TITLE
pam_aad.c:4:21: fatal error: sds/sds.h: No such file or directory

### ISSUE THREAD

**Issue by ghost** [CyberNinjas/pam_aad#56]
Attempting build on Centos 7. Missing header `sds.h`. 

```bash
$ make
  CC       pam_aad_la-pam_aad.lo
pam_aad.c:4:21: fatal error: sds/sds.h: No such file or directory
 #include <sds/sds.h>
                     ^
compilation terminated.
make: *** [pam_aad_la-pam_aad.lo] Error 1
```

Please advise which library contains `sds.h`.

Thanks!

**Comment by securityvoid** [comment]
@dougscc I believe that comes from libsdl.

**Comment by ghost** [comment]
@securityvoid, installing libsdl dev libraries does not do the trick, unfortunately. `sds/sds.h` is apparently part of redis, from which antirez has [forked a stand-alone sds](https://github.com/antirez/sds). Unfortunately I am not smart enough to get anything to link against it, yet. I'll keep plugging at it and let you know.

**Comment by maordadush** [comment]
@dougscc, How did you manage to solve this problem?

**Comment by ghost** [comment]
I did not. I gave up and went another route.

**Comment by securityvoid** [comment]
@dougscc I'm sorry that didn't work for you. The individual I had maintaining this project left the company and went to work somewhere else. 

We actively utilize this on Ubuntu and have libraries that work for that; but I haven't had the time to setup a CentOS environment to test this and see what the problem is.
